name: flux
version: 0.0.3
description: The beta version of the dart framework for Flux design pattern.
homepage: https://github.com/jakuub/flux
documentation: https://github.com/jakuub/flux
dependencies:
  tiles: any
  vacuum_persistent:
    git: https://github.com/vacuumlabs/persistent.git
dev_dependencies:
  mock: any
  unittest: any
